/**
 * @file
 *
 * Source for the bbox::rt::net::ssdp::DeviceInfo struct.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED BY THE IDL COMPILER FROM
 * IDL SOURCE FILE "bbox_rt_net_ssdp.bbidl"
 */

#include <bbox/rt/net/ssdp/DeviceInfo.h>

namespace bbox {
namespace rt {
namespace net {
namespace ssdp {

void DeviceInfo::ToBinary(bbox::enc::ToBinary &m) const
{
    m.Write(usn);
    m.Write(local_address);
    m.Write(device_address);
    m.Write(service_type);
    m.Write(location);
}

void DeviceInfo::FromBinary(bbox::enc::FromBinary &m)
{
    m.Read(usn);
    m.Read(local_address);
    m.Read(device_address);
    m.Read(service_type);
    m.Read(location);
}

void DeviceInfo::ToTextFormat(bbox::enc::ToTextFormat &m) const
{
    m.StartStructure();
    m.AddNamedValue("usn", usn);
    m.AddNamedValue("local_address", local_address);
    m.AddNamedValue("device_address", device_address);
    m.AddNamedValue("service_type", service_type);
    m.AddNamedValue("location", location);
    m.CompleteStructure();
}

void DeviceInfo::FromTextFormat(bbox::enc::FromTextFormat &m)
{
    m.StartStructure();
    m.DecodeNamedValue("usn", usn);
    m.DecodeNamedValue("local_address", local_address);
    m.DecodeNamedValue("device_address", device_address);
    m.DecodeNamedValue("service_type", service_type);
    m.DecodeNamedValue("location", location);
    m.CompleteStructure();
}

} // namespace ssdp
} // namespace net
} // namespace rt
} // namespace bbox

