/**
 * @file
 *
 * Implementation file for the ledsigns::casadelshade::CasaDelShadeLayout global.
 */

#include <ledsigns/casadelshade/CasaDelShadeLayout.h>

namespace ledsigns
{
    namespace casadelshade
    {

        common::Layout CasaDelShadeLayout{
            "Casa Del Shade",
            {
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },
                { 0 },

                { 1 },
                { 1 },
                { 1 },
                { 1 },
                { 1 },
                { 1 },
                { 1 },
                { 1 },
                { 1 },
                { 1 },
                { 1 },
                { 1 },
                { 1 },
                { 1 },
                { 1 },
                { 1 },
                { 1 },
                { 1 },
                { 1 },
                { 1 },
                { 1 },
                { 1 },
                { 1 },
                { 1 },
                { 1 },

                { 3 },
                { 3 },
                { 3 },
                { 3 },
                { 3 },
                { 3 },
                { 3 },
                { 3 },
                { 3 },
                { 3 },
                { 3 },

                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
                { 2 },
            }
        };

    } //namespace ledsigns::casadelshade
} // namespace ledsigns
