/**
 * @file
 *
 * Header for the mn::msgs::ButtonStates struct.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED BY THE IDL COMPILER FROM
 * IDL SOURCE FILE "mn_msgs.bbidl"
 */

#ifndef __mn_msgs_ButtonStates_H__
#define __mn_msgs_ButtonStates_H__

#include <bbox/enc/FromBinary.h>
#include <bbox/enc/FromTextFormat.h>
#include <bbox/enc/MsgTypeLibrary.h>
#include <bbox/enc/ToBinary.h>
#include <bbox/enc/ToTextFormat.h>

namespace mn {
namespace msgs {

class ButtonStates
{
public:
    ButtonStates() = default;
    ~ButtonStates() = default;
    ButtonStates(const ButtonStates&) = default;
    ButtonStates(ButtonStates&&) = default;
    ButtonStates &operator =(const ButtonStates&) = default;
    ButtonStates &operator =(ButtonStates&&) = default;

    void ToBinary(bbox::enc::ToBinary &m) const;
    void FromBinary(bbox::enc::FromBinary &m);
    void ToTextFormat(bbox::enc::ToTextFormat &m) const;
    void FromTextFormat(bbox::enc::FromTextFormat &m);

    bool back_state;
    bool play_state;
    std::vector<bool> button_states;

    static bbox::enc::MsgTypeLibrary::Registration<ButtonStates> g_msg_registration;
};

} // namespace msgs
} // namespace mn

#endif // __mn_msgs_ButtonStates_H__
