/**
 * @file
 *
 * Source for the mn::msgs::EmulatorCompleted struct.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED BY THE IDL COMPILER FROM
 * IDL SOURCE FILE "mn_msgs.bbidl"
 */

#include <mn/msgs/EmulatorCompleted.h>

namespace mn {
namespace msgs {

void EmulatorCompleted::ToBinary(bbox::enc::ToBinary &m) const
{
    (void)m;
}

void EmulatorCompleted::FromBinary(bbox::enc::FromBinary &m)
{
    (void)m;
}

void EmulatorCompleted::ToTextFormat(bbox::enc::ToTextFormat &m) const
{
    m.StartStructure();
    m.CompleteStructure();
}

void EmulatorCompleted::FromTextFormat(bbox::enc::FromTextFormat &m)
{
    m.StartStructure();
    m.CompleteStructure();
}

bbox::enc::MsgTypeLibrary::Registration<EmulatorCompleted>
    EmulatorCompleted::g_msg_registration("mn::msgs::EmulatorCompleted", []() { return new_message<mn::msgs::EmulatorCompleted>(); });

} // namespace msgs
} // namespace mn

