/**
 * @file
 *
 * Header for the mn::msgs::EmulatorCompleted struct.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED BY THE IDL COMPILER FROM
 * IDL SOURCE FILE "mn_msgs.bbidl"
 */

#ifndef __mn_msgs_EmulatorCompleted_H__
#define __mn_msgs_EmulatorCompleted_H__

#include <bbox/enc/FromBinary.h>
#include <bbox/enc/FromTextFormat.h>
#include <bbox/enc/MsgTypeLibrary.h>
#include <bbox/enc/ToBinary.h>
#include <bbox/enc/ToTextFormat.h>

namespace mn {
namespace msgs {

class EmulatorCompleted
{
public:
    EmulatorCompleted() = default;
    ~EmulatorCompleted() = default;
    EmulatorCompleted(const EmulatorCompleted&) = default;
    EmulatorCompleted(EmulatorCompleted&&) = default;
    EmulatorCompleted &operator =(const EmulatorCompleted&) = default;
    EmulatorCompleted &operator =(EmulatorCompleted&&) = default;

    void ToBinary(bbox::enc::ToBinary &m) const;
    void FromBinary(bbox::enc::FromBinary &m);
    void ToTextFormat(bbox::enc::ToTextFormat &m) const;
    void FromTextFormat(bbox::enc::FromTextFormat &m);

    static bbox::enc::MsgTypeLibrary::Registration<EmulatorCompleted> g_msg_registration;
};

} // namespace msgs
} // namespace mn

#endif // __mn_msgs_EmulatorCompleted_H__
