/**
 * @file
 *
 * Source for the mn::msgs::StartEmulator struct.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED BY THE IDL COMPILER FROM
 * IDL SOURCE FILE "mn_msgs.bbidl"
 */

#include <mn/msgs/StartEmulator.h>

namespace mn {
namespace msgs {

void StartEmulator::ToBinary(bbox::enc::ToBinary &m) const
{
    m.Write(game);
}

void StartEmulator::FromBinary(bbox::enc::FromBinary &m)
{
    m.Read(game);
}

void StartEmulator::ToTextFormat(bbox::enc::ToTextFormat &m) const
{
    m.StartStructure();
    m.AddNamedValue("game", game);
    m.CompleteStructure();
}

void StartEmulator::FromTextFormat(bbox::enc::FromTextFormat &m)
{
    m.StartStructure();
    m.DecodeNamedValue("game", game);
    m.CompleteStructure();
}

bbox::enc::MsgTypeLibrary::Registration<StartEmulator>
    StartEmulator::g_msg_registration("mn::msgs::StartEmulator", []() { return new_message<mn::msgs::StartEmulator>(); });

} // namespace msgs
} // namespace mn

