/**
 * @file
 *
 * Source for the mn::msgs::ButtonStates struct.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED BY THE IDL COMPILER FROM
 * IDL SOURCE FILE "mn_msgs.bbidl"
 */

#include <mn/msgs/ButtonStates.h>

namespace mn {
namespace msgs {

void ButtonStates::ToBinary(bbox::enc::ToBinary &m) const
{
    m.Write(back_state);
    m.Write(play_state);
    m.Write(button_states);
}

void ButtonStates::FromBinary(bbox::enc::FromBinary &m)
{
    m.Read(back_state);
    m.Read(play_state);
    m.Read(button_states);
}

void ButtonStates::ToTextFormat(bbox::enc::ToTextFormat &m) const
{
    m.StartStructure();
    m.AddNamedValue("back_state", back_state);
    m.AddNamedValue("play_state", play_state);
    m.AddNamedValue("button_states", button_states);
    m.CompleteStructure();
}

void ButtonStates::FromTextFormat(bbox::enc::FromTextFormat &m)
{
    m.StartStructure();
    m.DecodeNamedValue("back_state", back_state);
    m.DecodeNamedValue("play_state", play_state);
    m.DecodeNamedValue("button_states", button_states);
    m.CompleteStructure();
}

bbox::enc::MsgTypeLibrary::Registration<ButtonStates>
    ButtonStates::g_msg_registration("mn::msgs::ButtonStates");

} // namespace msgs
} // namespace mn

