/**
 * @file
 *
 * Source for the bbox::rt::net::AdapterInfo struct.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED BY THE IDL COMPILER FROM
 * IDL SOURCE FILE "bbox_rt_net.bbidl"
 */

#include <bbox/rt/net/AdapterInfo.h>

namespace bbox {
namespace rt {
namespace net {

void AdapterInfo::ToBinary(bbox::enc::ToBinary &m) const
{
    m.Write(system_name);
    m.Write(user_name);
    m.Write(description);
    m.Write(mac_address);
    m.Write(ip_addresses);
}

void AdapterInfo::FromBinary(bbox::enc::FromBinary &m)
{
    m.Read(system_name);
    m.Read(user_name);
    m.Read(description);
    m.Read(mac_address);
    m.Read(ip_addresses);
}

void AdapterInfo::ToTextFormat(bbox::enc::ToTextFormat &m) const
{
    m.StartStructure();
    m.AddNamedValue("system_name", system_name);
    m.AddNamedValue("user_name", user_name);
    m.AddNamedValue("description", description);
    m.AddNamedValue("mac_address", mac_address);
    m.AddNamedValue("ip_addresses", ip_addresses);
    m.CompleteStructure();
}

void AdapterInfo::FromTextFormat(bbox::enc::FromTextFormat &m)
{
    m.StartStructure();
    m.DecodeNamedValue("system_name", system_name);
    m.DecodeNamedValue("user_name", user_name);
    m.DecodeNamedValue("description", description);
    m.DecodeNamedValue("mac_address", mac_address);
    m.DecodeNamedValue("ip_addresses", ip_addresses);
    m.CompleteStructure();
}

} // namespace net
} // namespace rt
} // namespace bbox

