/**
 * @file
 *
 * Source for the bbox::http::debug::msgs::DebugReportNotification struct.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED BY THE IDL COMPILER FROM
 * IDL SOURCE FILE "bbox_http_debug_msgs.bbidl"
 */

#include <bbox/http/debug/msgs/DebugReportNotification.h>

namespace bbox {
namespace http {
namespace debug {
namespace msgs {

void DebugReportNotification::ToBinary(bbox::enc::ToBinary &m) const
{
    m.Write(contents_html);
}

void DebugReportNotification::FromBinary(bbox::enc::FromBinary &m)
{
    m.Read(contents_html);
}

void DebugReportNotification::ToTextFormat(bbox::enc::ToTextFormat &m) const
{
    m.StartStructure();
    m.AddNamedValue("contents_html", contents_html);
    m.CompleteStructure();
}

void DebugReportNotification::FromTextFormat(bbox::enc::FromTextFormat &m)
{
    m.StartStructure();
    m.DecodeNamedValue("contents_html", contents_html);
    m.CompleteStructure();
}

bbox::enc::MsgTypeLibrary::Registration<DebugReportNotification>
    DebugReportNotification::g_msg_registration("bbox::http::debug::msgs::DebugReportNotification", []() { return new_message<bbox::http::debug::msgs::DebugReportNotification>(); });

} // namespace msgs
} // namespace debug
} // namespace http
} // namespace bbox

