/**
 * @file
 *
 * Source for the bbox::http::debug::msgs::EnableRequest struct.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED BY THE IDL COMPILER FROM
 * IDL SOURCE FILE "bbox_http_debug_msgs.bbidl"
 */

#include <bbox/http/debug/msgs/EnableRequest.h>

namespace bbox {
namespace http {
namespace debug {
namespace msgs {

void EnableRequest::ToBinary(bbox::enc::ToBinary &m) const
{
    m.Write(enabled);
    m.Write(debug_enables);
}

void EnableRequest::FromBinary(bbox::enc::FromBinary &m)
{
    m.Read(enabled);
    m.Read(debug_enables);
}

void EnableRequest::ToTextFormat(bbox::enc::ToTextFormat &m) const
{
    m.StartStructure();
    m.AddNamedValue("enabled", enabled);
    m.AddNamedValue("debug_enables", debug_enables);
    m.CompleteStructure();
}

void EnableRequest::FromTextFormat(bbox::enc::FromTextFormat &m)
{
    m.StartStructure();
    m.DecodeNamedValue("enabled", enabled);
    m.DecodeNamedValue("debug_enables", debug_enables);
    m.CompleteStructure();
}

bbox::enc::MsgTypeLibrary::Registration<EnableRequest>
    EnableRequest::g_msg_registration("bbox::http::debug::msgs::EnableRequest", []() { return new_message<bbox::http::debug::msgs::EnableRequest>(); });

} // namespace msgs
} // namespace debug
} // namespace http
} // namespace bbox

