/**
 * @file
 *
 * Header for the bbox::http::debug::msgs::QueryResponse struct.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED BY THE IDL COMPILER FROM
 * IDL SOURCE FILE "bbox_http_debug_msgs.bbidl"
 */

#ifndef __bbox_http_debug_msgs_QueryResponse_H__
#define __bbox_http_debug_msgs_QueryResponse_H__

#include <bbox/enc/FromBinary.h>
#include <bbox/enc/FromTextFormat.h>
#include <bbox/enc/MsgTypeLibrary.h>
#include <bbox/enc/ToBinary.h>
#include <bbox/enc/ToTextFormat.h>

#include <bbox/http/debug/msgs/QueryResponseEntry.h>

namespace bbox {
namespace http {
namespace debug {
namespace msgs {

class QueryResponse
{
public:
    QueryResponse() = default;
    ~QueryResponse() = default;
    QueryResponse(const QueryResponse&) = default;
    QueryResponse(QueryResponse&&) = default;
    QueryResponse &operator =(const QueryResponse&) = default;
    QueryResponse &operator =(QueryResponse&&) = default;

    void ToBinary(bbox::enc::ToBinary &m) const;
    void FromBinary(bbox::enc::FromBinary &m);
    void ToTextFormat(bbox::enc::ToTextFormat &m) const;
    void FromTextFormat(bbox::enc::FromTextFormat &m);

    std::string request_id;
    std::vector<QueryResponseEntry> entries;

    static bbox::enc::MsgTypeLibrary::Registration<QueryResponse> g_msg_registration;
};

} // namespace msgs
} // namespace debug
} // namespace http
} // namespace bbox

#endif // __bbox_http_debug_msgs_QueryResponse_H__
