/**
 * @file
 *
 * Header for the bbox::http::debug::msgs::QueryRequest struct.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED BY THE IDL COMPILER FROM
 * IDL SOURCE FILE "bbox_http_debug_msgs.bbidl"
 */

#ifndef __bbox_http_debug_msgs_QueryRequest_H__
#define __bbox_http_debug_msgs_QueryRequest_H__

#include <bbox/enc/FromBinary.h>
#include <bbox/enc/FromTextFormat.h>
#include <bbox/enc/MsgTypeLibrary.h>
#include <bbox/enc/ToBinary.h>
#include <bbox/enc/ToTextFormat.h>

namespace bbox {
namespace http {
namespace debug {
namespace msgs {

class QueryRequest
{
public:
    QueryRequest() = default;
    ~QueryRequest() = default;
    QueryRequest(const QueryRequest&) = default;
    QueryRequest(QueryRequest&&) = default;
    QueryRequest &operator =(const QueryRequest&) = default;
    QueryRequest &operator =(QueryRequest&&) = default;

    void ToBinary(bbox::enc::ToBinary &m) const;
    void FromBinary(bbox::enc::FromBinary &m);
    void ToTextFormat(bbox::enc::ToTextFormat &m) const;
    void FromTextFormat(bbox::enc::FromTextFormat &m);

    bool operator ==(const QueryRequest &other) const
    {
        return (request_id == other.request_id)
            && (query == other.query);
    }

    bool operator !=(const QueryRequest &other) const
    {
        return (request_id != other.request_id)
            || (query != other.query);
    }

    std::string request_id;
    std::string query;

    static bbox::enc::MsgTypeLibrary::Registration<QueryRequest> g_msg_registration;
};

} // namespace msgs
} // namespace debug
} // namespace http
} // namespace bbox

#endif // __bbox_http_debug_msgs_QueryRequest_H__
