/**
 * @file
 *
 * Source for the bbox::http::debug::msgs::QueryResponseChild struct.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED BY THE IDL COMPILER FROM
 * IDL SOURCE FILE "bbox_http_debug_msgs.bbidl"
 */

#include <bbox/http/debug/msgs/QueryResponseChild.h>

namespace bbox {
namespace http {
namespace debug {
namespace msgs {

void QueryResponseChild::ToBinary(bbox::enc::ToBinary &m) const
{
    m.Write(name);
    m.Write(path);
    m.Write(short_description);
}

void QueryResponseChild::FromBinary(bbox::enc::FromBinary &m)
{
    m.Read(name);
    m.Read(path);
    m.Read(short_description);
}

void QueryResponseChild::ToTextFormat(bbox::enc::ToTextFormat &m) const
{
    m.StartStructure();
    m.AddNamedValue("name", name);
    m.AddNamedValue("path", path);
    m.AddNamedValue("short_description", short_description);
    m.CompleteStructure();
}

void QueryResponseChild::FromTextFormat(bbox::enc::FromTextFormat &m)
{
    m.StartStructure();
    m.DecodeNamedValue("name", name);
    m.DecodeNamedValue("path", path);
    m.DecodeNamedValue("short_description", short_description);
    m.CompleteStructure();
}

} // namespace msgs
} // namespace debug
} // namespace http
} // namespace bbox

