/**
 * @file
 *
 * Source for the bbox::http::debug::msgs::QueryResponseEntry struct.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED BY THE IDL COMPILER FROM
 * IDL SOURCE FILE "bbox_http_debug_msgs.bbidl"
 */

#include <bbox/http/debug/msgs/QueryResponseEntry.h>

namespace bbox {
namespace http {
namespace debug {
namespace msgs {

void QueryResponseEntry::ToBinary(bbox::enc::ToBinary &m) const
{
    m.Write(path);
    m.Write(parent_path);
    m.Write(children);
    m.Write(report);
}

void QueryResponseEntry::FromBinary(bbox::enc::FromBinary &m)
{
    m.Read(path);
    m.Read(parent_path);
    m.Read(children);
    m.Read(report);
}

void QueryResponseEntry::ToTextFormat(bbox::enc::ToTextFormat &m) const
{
    m.StartStructure();
    m.AddNamedValue("path", path);
    m.AddNamedValue("parent_path", parent_path);
    m.AddNamedValue("children", children);
    m.AddNamedValue("report", report);
    m.CompleteStructure();
}

void QueryResponseEntry::FromTextFormat(bbox::enc::FromTextFormat &m)
{
    m.StartStructure();
    m.DecodeNamedValue("path", path);
    m.DecodeNamedValue("parent_path", parent_path);
    m.DecodeNamedValue("children", children);
    m.DecodeNamedValue("report", report);
    m.CompleteStructure();
}

} // namespace msgs
} // namespace debug
} // namespace http
} // namespace bbox

